author: P Bellec, S Jbabdi, R Cameron Cradock
bibtex_bibfiles:
- ../paper.bib
copyright: '2021'
exclude_patterns: []
execute:
  cache: ''
  exclude_patterns: []
  execute_notebooks: auto
  timeout: -1
html:
  baseurl: ''
  extra_footer: ''
  extra_navbar: Powered by <a href="https://jupyterbook.org">Jupyter Book</a>
  favicon: ''
  google_analytics_id: ''
  home_page_in_navbar: true
  use_edit_page_button: false
  use_issues_button: false
  use_repository_button: false
launch_buttons:
  binderhub_url: https://binder-mcgill.conp.cloud
  notebook_interface: jupyterlab
  thebe: false
logo: ../images/neurolibre-logo.png
parse:
  myst_enable_extensions:
  - html_image
repository:
  branch: main
  path_to_book: content
  url: https://github.com/roboneurolibre/editorial_parcellation
sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
title: Parcellating the parcellation issue
